[book]
authors = ["YouSafe"]
language = "en"
multilingual = false
src = "src"
title = "Tilde Issue Reprod"

[output.html]
additional-css = ["katex.min.css"]
additional-js = ["contrib/copy-tex.min.js"]

[preprocessor.katex]
output = "htmlAndMathml"
after = ["links"]
no-css = true
include-src = false
