name: Deploy

on:
  push:
    branches:
      - main # Run on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install latest mdBook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Download and extract mdBook-KaTeX
        run: |
          url="https://github.com/lzanini/mdbook-katex/releases/download/0.9.0-binaries/mdbook-katex-v0.9.0-x86_64-unknown-linux-gnu.tar.gz"
          curl -o 'mdbook-katex.tar.gz' -J -L $url
          tar -xzvf 'mdbook-katex.tar.gz'

      - name: add bin to path
        run: echo "$(pwd)" >> $GITHUB_PATH

      - name: Download KaTeX CSS and fonts
        run: python3 download_static_css.py

      - name: Build Book
        run: mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book' # This is where the built book will be located

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
